language: r

cache: packages

warnings_are_errors: false

addons:
    apt:
        packages:
            - sshpass
            
after_success:
    - mkdir build
    - mv * build
    - ls -al build
    - tar -czf package.tgz build
    - ls -al
    - export SSHPASS=$DEPLOY_PASS
    - echo DEPLOY_HOST=$DEPLOY_HOST
    - echo DEPLOY_PATH=$DEPLOY_PATH
    - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    