sudo: required

language: ruby

services:
 - docker

before_install:
 - docker build -t sagebionetworks/mpower-processing .

script:
 # Note:  Omitting '--no-manual' below results in "Error in texi2dvi(...):  pdflatex is not available"
 - docker run -w /mPowerProcessing -it -e SYNAPSE_USERNAME=$SYNAPSE_USERNAME -e SYNAPSE_APIKEY=$SYNAPSE_APIKEY -e BRIDGE_USERNAME=$BRIDGE_USERNAME -e BRIDGE_PASSWORD=$BRIDGE_PASSWORD sagebionetworks/mpower-processing R --no-save < tests/testthat.R
            
after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" https://index.docker.io/v1
 - test $TRAVIS_PULL_REQUEST == "false" && docker push sagebionetworks/power-processing
     